### ISSUE TITLE
Can do without Bitcoin transaction?

### ISSUE THREAD

**Issue by unwriter** [interplanaria/bitbus#3]
The sync requires dealing with bitcoin transactions and keys even though it's not being used yet. 

Think about whether this can be just extracted out to simplify the module.

**Comment by golangdaddy** [comment]
Is this ticket a response to the request to make 'bitbus new' optional?

Could you please give more details about how keys are required for the sync process?

**Comment by unwriter** [comment]
This was to get rid of the Insight dependency on insight endpoints. This feature will be important in the future but at the moment it's not being used but was just overloading the insight endpoints and sometimes goes down with along with the insight.

Getting rid of the dependency made sure that bitbus doesn't depend on 3rd party insight services https://github.com/interplanaria/bitbus/commit/e10a703264496ffd9f3cf3ce8d07e293496dd833
