### ISSUE TITLE
FEATURE: ability to specify the host file path for bitbus to save the `bus` dir

### ISSUE THREAD

**Issue by gWOLF3** [interplanaria/bitbus#8]
**Feature Request:** Possible way to specify path on host file system for Bitbus to save and write `bus` directory. 

**Possible use case:** Running shared volume mount with separate services, (such as on kubernetes).  

**Current Behavior:** `bitbus start` command looks to find `.json` file in path with valid "bitbus" key. It creates `bus` folder in current file path from which command was ran. In bitbusbox impl, this is on the `/mnt` path from which we also copy the `run.sh` file. Problem here is that if we are wanting to write the bus to a shared volume, we need to mount it here, overwriting our run and json file. 

**Tmp Workaround:** To workaround this issue, without the requested feature, it is also possible to change the entry point to a different, clean fs location on which to mount, and instead simply export the locations on the `run.sh` and `<your.json>` to your PATH, so that they are found on `start`. This way should work but is a little hacked. 

**Possible Implementations:** could be 1) using command line flags;  `--buspath <yourpath>` or 2) env variable ; `export BUSPATH=<yourpath>`

**Comment by unwriter** [comment]
resolved with https://github.com/interplanaria/bitbus/commit/0cc593e86e6afb11b013d22e3385d86344f65143

See https://bitbus.network/docs#/?id=_8-custom-bus-path to learn more. 

Hope this solves all the problems. Otherwise, please reopen, or open a new issue.
